# workflow name
name: CI

# trigger events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs to run
jobs:
  build:
    name: Build CLI application
    runs-on: ubuntu-latest
    steps:

      # step 1: set up go
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get

      # step 4: build module
      - name: go build
        run: go build -o pz
